name: Push nupkg

on:
  watch:
    types: [started]
  push:
    tags: 
      - V.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: dotnet restore
      run: dotnet restore
    - name:  dotnet Build
      run: dotnet build -c Release --no-restore
    - name: dotnet pack
      run: dotnet pack src/Fieldclimate.Pessl.Domain/Fieldclimate.Pessl.Domain.csproj --no-build --no-restore -c Release -o nupkgs
    - name: dotnet nuget push
      run: dotnet nuget push nupkgs/*.nupkg -s nuget.org -k ${{ env.NUGET_API_KEY }}
        
